[package]
name = "granit-parser-benchmarks"
version = "0.0.0"
publish = false
edition = "2021"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[features]
default = ["error_messages", "std", "comments"]
comments = ["granit-parser/comments"]
error_messages = ["granit-parser/error_messages"]
std = ["granit-parser/std"]
debug_prints = ["std", "granit-parser/debug_prints"]

[dependencies]
granit-parser = { path = "../..", default-features = false }

[dev-dependencies]
divan = { version = "5.0.2", package = "codspeed-divan-compat" }

[[bench]]
name = "parser"
harness = false

[lints.rust]
unsafe_code = "forbid"
unsafe_op_in_unsafe_fn = "deny"
